### ISSUE TITLE
Error while adding new users in Ko3 with Jelly on postgresql

### ISSUE THREAD

**Issue by KRTac** [cbandy/kohana-postgresql#1]
(copy of a [kohana forum post](http://forum.kohanaphp.com/comments.php?DiscussionID=5303))

I'm trying to add a new user to the users table with:

```
Jelly::factory('user')
    ->set(array(
        'username' => 'user',
        'email' => 'email@example.com',
        'password' => 'test123',
        'password_confirm' => 'test123',
    ))->save();
```

but I'm getting a error:

```
Database_Exception [ 0 ]: ERROR: column "users.username" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: ...users" WHERE "users"."username" = 'user' ORDER BY "users"."u...
[ SELECT COUNT(*) AS "total" FROM "users" WHERE "users"."username" = 'user' ORDER BY "users"."username" ASC ]
```

I am using Jelly with the jelly-auth module and postgresql as the database. With mysql all works well, so I guess it's a driver problem.

**Comment by KRTac** [comment]
It may not be a postgresql driver bug, but a [jelly specific](http://github.com/jonathangeiger/kohana-jelly/issues/issue/95) bug.

**Comment by cbandy** [comment]
Yes, this is a SQL syntax error caused by Jelly
