### ISSUE TITLE
pg_send_query() error

### ISSUE THREAD

**Issue by vrbas** [cbandy/kohana-postgresql#6]
I'm getting these 2 erros while working with your driver:
pg_send_query(): There are results on this connection. Call pg_get_result() until it returns FALSE ~ MODPATH/database/classes/kohana/database/postgresql.php [ 153 ] FATAL
ErrorException [ 8 ]: pg_send_query(): Cannot set connection to blocking mode ~ MODPATH/database/classes/kohana/database/postgresql.php [ 153 ]
I'm getting these errors while doing long-running SQL UPDATE. Other queries are ok. Is there any PHP configuration which limits it?

What is the main purpose of using pg_send_query() instead classic pg_query()?

**Comment by cbandy** [comment]
It lets us get detailed error information from the result resource. `pg_get_result()` returns a result resource even when there is an error. I think it is also required detect when any `COPY` SQL has been executed.

Does this error appear when you are doing _one_ long-running `UPDATE` or when you are running _multiple_ `UPDATE` statements in one call?

**Comment by vrbas** [comment]
It's one long-running <code>UPDATE</code>.
This statement updates data which came from HTML form. When I send a short text, everything is fine. I got this error when the input data is > approximately 20 kB.
It's confusing that I get this error on webhosting, but not on local machine. And I didn't find any relevant difference among setting of both servers.

**Comment by cbandy** [comment]
It looks like you're using Kohana 3.0, right?

This error happens when the _previous_ query was multiple statements. What query do you run _before_ the query that causes the error?

**Comment by vrbas** [comment]
You're right. It's Kohana 3.0.8.
This is simplified log of queries:
simple <code>SELECT</code>
simple <code>SELECT</code>
<code>START TRANSACTION</code>
long-running <code>UPDATE</code>

**Comment by cbandy** [comment]
Are you executing all of those in a single call to `query()`? The (Kohana) API doesn't have any support for multiple `SELECT` in one call.

I've fixed `query()` to handle compound statements, but only when the first argument is neither `Database::INSERT` nor `Database::SELECT`:

``` php
<?php

$db->query(NULL, 'START TRANSACTION ; UPDATE kohana_test_table SET value = 5 ; COMMIT');
$db->query(Database::SELECT, 'SELECT * FROM kohana_test_table');
```

You can cherry-pick this one commit if necessary. Does this solve your issue?

**Comment by vrbas** [comment]
one SQL statement = one <code>query()</code> call.
So unfortunately your fix didn't help.

I made simple test on webhosting, where I get error:

<pre>
$result = DB::query(Database::UPDATE, "UPDATE page SET body = '
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut rutrum placerat erat, vitae blandit nunc convallis at. Aenean eu volutpat neque. Quisque facilisis dapibus viverra.  
' WHERE id = 35;
")->execute();
</pre>

This is ok.

<pre>
$result = DB::query(Database::UPDATE, "UPDATE page SET body = '
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut rutrum placerat erat, vitae blandit nunc convallis at. Aenean eu volutpat neque. Quisque facilisis dapibus viverra.
/*VERY LONG TEXT - approximately 100 lines of sample text*/
' WHERE id = 35;
")->execute();
</pre>

I get this error: <code>ErrorException [ 8 ]: pg_send_query(): There are results on this connection. Call pg_get_result() until it returns FALSE ~ MODPATH/database/classes/kohana/database/postgresql.php [ 153 ] FATAL</code>

**Comment by cbandy** [comment]
Hmm. It sounds like the very long text has SQL in it, at least a semi-colon. Are you calling `escape()` on the data first?

**Comment by cbandy** [comment]
Actually, the call that fails is not the offender. It is the call _before_ that leaves results unfetched.

You're certain that there is no other query before the one with long text?

**Comment by vrbas** [comment]
<code>VERY LONG TEXT</code> is only abbreviation for another "Lorem ipsum..." sentences - same as in first statement - no SQL in it, no semi-colon. Only difference between 1st and 2nd statement is in length of updated text.
I made this simple test in method before() of default Controller. So I'm nearly 100% certain there is no other query before. So it's probably not issue of your module...

**Comment by vrbas** [comment]
My conclusion is that it's the issue of pg_send_query function itself.
see http://stackoverflow.com/questions/865017/pg-send-query-cannot-set-connection-to-blocking-mode

**Comment by cbandy** [comment]
Interesting. Are you using persistent connections by any chance?

**Comment by vrbas** [comment]
I'm using normal connection. I got same result also without using DB class.
<code>$con = pg_connect('xxx', PGSQL_CONNECT_FORCE_NEW); pg_send_query ($con, 'simple UPDATE');</code> OK
<code>$con = pg_connect('xxx', PGSQL_CONNECT_FORCE_NEW); pg_send_query ($con, 'long-running UPDATE');</code> "Cannot set connection to blocking mode" error
<code>$con = pg_connect('xxx', PGSQL_CONNECT_FORCE_NEW); pg_query ($con, 'long-running UPDATE');</code> OK

**Comment by cbandy** [comment]
Thank you for your patience and tests. Does this commit work?

**Comment by vrbas** [comment]
Actually your last commit is nearly the same as my temporary(?) modification of your code. I use this modification for more than 1 month and it works on both servers.

<pre>
try {
    $result = pg_query($this->_connection, $sql);
} catch (ErrorException $e) {
    $result = false;
}

if (! $result) {
    throw new Database_Exception(':error [ :query ]',
       array(':error' => pg_last_error($this->_connection), ':query' => $sql));
}
</pre>
