### ISSUE TITLE
LASTVAL() spoils my transaction

### ISSUE THREAD

**Issue by chandeeland** [cbandy/kohana-postgresql#7]
This is more of a design problem.

I have a join table which uses a multi-key primary.

I cannot have primary_key config set because many of my tables do not have single primary keys, and thus do not have a simple 'id' column for the RETURNING statement.

When I attempt to insert into this kind of table inside of a transaction using this kohana-postgresql library,  it tries to run a "SELECT LASTVAL()"  however because no sequence has been NEXTVAL()'d I trigger a db error which spoils my transaction for future queries.

Worse,  an exception is only thrown when the next statement is run, not when the "SELECT LASTVAL() statement is run...

my proposed solution is to allow the user to pass in $sql with a custom RETURNING statement.  and if found, then to act as if _config['primary_key'] was set for that query with the custom RETURNING being used.

```
    public function query($type, $sql, $as_object = FALSE, array $params = NULL)
    {
            $this->_connection or $this->connect();
            $custom_returning = false;

            if ( ! empty($this->_config['profiling']))
            {
                    // Benchmark this query for the current instance
                    $benchmark = Profiler::start("Database ({$this->_instance})", $sql);
            }

            try
            {
                    if (stripos($sql, ' RETURNING '))
                    {
                            $custom_returning = true;
                    }
                    else if ($type === Database::INSERT AND $this->_config['primary_key'])
                    {
                            $sql .= ' RETURNING '.$this->quote_identifier($this->_config['primary_key']);
                    }
                    ...


                    ....
                    if ($type === Database::INSERT)
                    {
                            if ($this->_config['primary_key'] || $custom_returning)
                            {
                                    // Fetch the first column of the last row
                                    $insert_id = pg_fetch_result($result, $rows - 1, 0);
                            }
                            elseif ($insert_id = pg_send_query($this->_connection, 'SELECT LASTVAL()'))
                            {
                                    if ($result = pg_get_result($this->_connection) AND pg_result_status($result) === PGSQL_TUPLES_OK)
                                    {
                                            $insert_id = pg_fetch_result($result, 0);
                                    }
                            }

                            return array($insert_id, $rows);
                    }
                    ....
```

**Comment by cbandy** [comment]
Are you using another library that forces the $type to be Database::INSERT? You can use Database::SELECT to retrieve results from any RETURNING statement.

I think scanning the query won't work, since it contains literal data as well as SQL. There's been discussion of changing the Kohana API, but I haven't visited it in a while: http://dev.kohanaframework.org/issues/2188

**Comment by chandeeland** [comment]
no other libraries... i'm only using Model_Database and write my query manually.  However I am indeed passing type as Database::INSERT.  using Database::SELECT would work, thanks for the advice.
