### ISSUE TITLE
pg_fetch_object error

### ISSUE THREAD

**Issue by synchrone** [cbandy/kohana-postgresql#8]
This may be some php bug, but Kohana_Database_PostgreSQL_Result::current() method seems to be using pg_fetch_object for getting models right from db resource.
In the mean time, pg_fetch_object first sets all the fields, then call __construct(), which is fatal when it comes to ORM models.

Given that:
`lamp@lamp:~$ cat test.php`

``` php
<?php

class user{
    public function __set($k,$v){
        echo 'setting '.$k. ' = '.$v.PHP_EOL;
    }
    public function __construct(){
        echo 'ctor'.PHP_EOL;
    }
}
pg_connect('host=localhost port=5432 dbname=trackerDB user=test password=test');

$res = pg_query('select id,username from users limit 1');

$user = pg_fetch_object($res,0,'user');
```

``` lamp@lamp:~$ php test.php
setting id = 23266
setting username = tiss
ctor

```

And since we have **ORM::_initialize()** and subsequent **ORM::clear()** call in all the ORM model constructors we won't even be able to instantiate those objects, as **_object** field is not yet filled with needed column info.

Maybe this is a PHP bug, but this issue can be worked around in this module as well
```

**Comment by cbandy** [comment]
This behavior is expected. The [MySQL driver](http://www.php.net/manual/mysqli-result.fetch-object) does the same thing, and there have been [numerous](https://bugs.php.net/46105) [bug](https://bugs.php.net/48487) [reports](https://bugs.php.net/50636) discussing the issue. `PDO::FETCH_PROPS_LATE` does what you're looking for, but no other drivers behave this way.

It is possible that the MySQL driver in PHP 5.2.14 [behaves differently](https://bugs.php.net/53177).
